### PR TITLE
Add parcel

### LINKED ISSUE #34: Hot reloading
Enable hot reloading of the server.
Parcel or nodemon

### PR DESCRIPTION
**Pull request by vine-d**
Added parcel-bundler. Closes #34 
I think it is still necessary to make parcel-bundler nor run when not in development mode.
Also need more tests on hot reload behaviour to confirm its working appropriately.

### CODE REVIEW

**Comment by samjam48** [comment]
Cool. Are you able to fix so that it runs only during development mode and not in production?

**Comment by aliahsan07** [comment]
working fine in development mode

**Comment by vine-d** [comment]
> Cool. Are you able to fix so that it runs only during development mode and not in production?

done.

**Comment by aliahsan07** [comment]
This might be a dumb question but what does it mean for hmr to run in production? Isn't it by definition only working when we're making changes to code and hit save which is not applicable for production builds.

**Comment by caiokf** [comment]
@aliahsan07 I think what they meant is that parcel is a bit different in the sense that hmr needs to use a specific middleware to "refresh" the express server when parcel updates the bundle. And to run only in prod, means, not adding this middleware when not in dev. @vine-d can correct me if that is not it

**Comment by vine-d** [comment]
Exactly the point was just to not load parcel-bundler on top of express when in production.

**Pull request merged**
